name: DockerHub README
on:
  push:
    branches: [ master ]
    paths:
      - ./docs/DOCKERHUB_README.md

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: xakep666/licensevalidator
          README_FILEPATH: ./docs/DOCKERHUB_README.md
